/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

// See https://github.com/Ail-nare/Modulable-CXX-Main for library's documentation and updates

#ifndef CXX_MAIN_HPP
#define CXX_MAIN_HPP

#include <type_traits>

#define main(...)   mainCPP(__VA_ARGS__);                           \
                    int main(int ac, char **argv, char **env)       \
                    { return declMain(ac, argv, env, &mainCPP); }   \
                    int mainCPP(__VA_ARGS__)


inline int declMain(int, char **, char **, int (*mainFunc)())
{
    return mainFunc();
}

template <typename T, typename std::enable_if<std::is_arithmetic<T>::value, int>::type=0>
inline int declMain(int ac, char **, char **, int (*mainFunc)(T))
{
    return mainFunc(ac);
}

template <typename T, typename std::enable_if<!std::is_arithmetic<T>::value, int>::type=0>
inline int declMain(int, char **av, char **, int (*mainFunc)(T))
{
    return mainFunc(av);
}

template <typename T1, typename T2, typename std::enable_if<std::is_arithmetic<T1>::value, int>::type=0>
inline int declMain(int ac, char **av, char **, int (*mainFunc)(T1, T2))
{
    return mainFunc(ac, av);
}

template <typename T1, typename T2, typename std::enable_if<!std::is_arithmetic<T1>::value, int>::type=0>
inline int declMain(int, char **av, char **env, int (*mainFunc)(T1, T2))
{
    return mainFunc(av, env);
}

template <typename ...Ts, typename std::enable_if<(sizeof...(Ts) == 3), int>::type=0>
inline int declMain(int ac, char **av, char **env, int (*mainFunc)(Ts...))
{
    return mainFunc(ac, av, env);
}

template <typename ...Ts, typename std::enable_if<(sizeof...(Ts) > 3), int>::type=0>
inline int declMain(int, char **, char **, int (*)(Ts...))
{
    static_assert(sizeof...(Ts) <= 3, "Your main can't have more than 3 arguments as parameters");
    return 0;
}

#endif //CXX_MAIN_HPP